# Generated by Django 5.0.1 on 2026-01-02 20:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Mobile device identifier', max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium subscription status')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('scripture_references', models.JSONField(blank=True, default=list, help_text='List of scripture references')),
                ('history', models.TextField(blank=True, help_text='Historical background of the hymn', null=True)),
                ('meter', models.CharField(blank=True, max_length=50, null=True)),
                ('key_signature', models.CharField(blank=True, max_length=10, null=True)),
                ('time_signature', models.CharField(blank=True, max_length=10, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Requires premium subscription')),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hymns', to='hymns.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hymns', to='hymns.category')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='hymns.hymn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('piano', 'Piano Accompaniment'), ('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('full', 'Full Choir')], max_length=20)),
                ('file', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('bitrate', models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='hymns.hymn')),
            ],
            options={
                'ordering': ['hymn', 'audio_type'],
            },
        ),
        migrations.CreateModel(
            name='HymnNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='Allow other users to see this note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hymns.hymn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hymn_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.hymn')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.playlist')),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='hymns',
            field=models.ManyToManyField(related_name='playlists', through='hymns.PlaylistHymn', to='hymns.hymn'),
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Upload PDF file', null=True, upload_to='sheet_music/%Y/%m/%d/')),
                ('url', models.URLField(blank=True, help_text='Or provide external URL (e.g., Google Drive, Dropbox)', max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sheet_music/thumbnails/%Y/%m/%d/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail URL if using external URL', max_length=500, null=True)),
                ('page_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_premium', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hymn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_music', to='hymns.hymn')),
            ],
            options={
                'verbose_name_plural': 'Sheet Music',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('product_id', models.CharField(help_text='Product ID from app store', max_length=255)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from app store', max_length=255, null=True, unique=True)),
                ('original_transaction_id', models.CharField(blank=True, help_text='Original transaction ID for subscriptions', max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20, null=True)),
                ('receipt_data', models.TextField(blank=True, help_text='Receipt data from app store', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_chorus', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order of verse in hymn')),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='hymns.hymn')),
            ],
            options={
                'ordering': ['order', 'verse_number'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='hymns_user_email_51c0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_premium'], name='hymns_user_is_prem_b36936_idx'),
        ),
        migrations.AddIndex(
            model_name='hymn',
            index=models.Index(fields=['number'], name='hymns_hymn_number_a91c64_idx'),
        ),
        migrations.AddIndex(
            model_name='hymn',
            index=models.Index(fields=['category'], name='hymns_hymn_categor_80edd2_idx'),
        ),
        migrations.AddIndex(
            model_name='hymn',
            index=models.Index(fields=['title'], name='hymns_hymn_title_99a253_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='hymns_favor_user_id_4781b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hymn')},
        ),
        migrations.AlterUniqueTogether(
            name='audiofile',
            unique_together={('hymn', 'audio_type')},
        ),
        migrations.AddIndex(
            model_name='hymnnote',
            index=models.Index(fields=['user', 'hymn'], name='hymns_hymnn_user_id_34bc36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisthymn',
            unique_together={('playlist', 'hymn')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'created_at'], name='hymns_playl_user_id_11cd14_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='hymns_subsc_user_id_0d28fb_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['transaction_id'], name='hymns_subsc_transac_f6240a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='hymns_subsc_expires_33d65c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('hymn', 'verse_number', 'is_chorus')},
        ),
    ]
