# Generated by Django 5.0.1 on 2026-01-02 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Denominations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DenominationHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Hymn number in this denomination/period', validators=[django.core.validators.MinValueValidator(1)])),
                ('hymn_period', models.CharField(blank=True, choices=[('new', 'New'), ('old', 'Old')], help_text='Required for Catholic hymns. Old and New have separate numbering sequences.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Denomination Hymn',
                'verbose_name_plural': 'Denomination Hymns',
                'ordering': ['denomination', 'hymn_period', 'number'],
            },
        ),
        migrations.AlterModelOptions(
            name='hymn',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='hymn',
            name='hymns_hymn_number_a91c64_idx',
        ),
        migrations.RemoveField(
            model_name='hymn',
            name='number',
        ),
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.TextField(help_text="Lyrics can vary by denomination (e.g., 'You' vs 'Thou')"),
        ),
        migrations.AddField(
            model_name='denominationhymn',
            name='denomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hymns', to='hymns.denomination'),
        ),
        migrations.AddField(
            model_name='denominationhymn',
            name='hymn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_hymns', to='hymns.hymn'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hymn',
            name='denominations',
            field=models.ManyToManyField(blank=True, help_text='Hymns can belong to multiple denominations with different numbers', related_name='hymn_set', through='hymns.DenominationHymn', to='hymns.denomination'),
        ),
        migrations.AddField(
            model_name='verse',
            name='denomination_hymn',
            field=models.ForeignKey(blank=True, help_text='Verses are linked to a specific denomination/period combination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='hymns.denominationhymn'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('denomination_hymn', 'verse_number', 'is_chorus')},
        ),
        migrations.AddIndex(
            model_name='denominationhymn',
            index=models.Index(fields=['denomination', 'hymn_period', 'number'], name='hymns_denom_denomin_b589df_idx'),
        ),
        migrations.AddIndex(
            model_name='denominationhymn',
            index=models.Index(fields=['denomination', 'hymn_period'], name='hymns_denom_denomin_3f32a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='denominationhymn',
            unique_together={('denomination', 'hymn_period', 'number')},
        ),
        migrations.RemoveField(
            model_name='verse',
            name='hymn',
        ),
    ]
